[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
counter_program = "4BnwJ3bBtRWU5yunMkW76qnVjwYFRrb2FRQT4zPKxcaj"

[programs.localnet]
counter_program = "7E8ibwHZTGCkobE9DkRVYss9LksviexqomAbBkpBJ1qF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
