[package]
name = "ecom-contract"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "2.0.1"

[lib]
name = "ecomcontract"
crate-type = ["cdylib", "lib"]